name: Create Folder Structure and Placeholder Files

on:
  workflow_dispatch:

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create folder structure and placeholder files
        run: |
          import os

          # Define the folder structure and placeholder content
          files = {
              "Python_Fall_2025/Assignment_1/dataset.csv": "Placeholder content for dataset.csv",
              "Python_Fall_2025/Assignment_2/dataset.csv": "Placeholder content for dataset.csv",
              "Python_Fall_2025/Assignment_3/dataset.csv": "Placeholder content for dataset.csv",
              "Global_Scholars_2025/Assignment_1/survey_results.csv": "Placeholder content for survey_results.csv",
              "Global_Scholars_2025/Assignment_2/demographic_data.csv": "Placeholder content for demographic_data.csv",
              "Global_Scholars_2025/Assignment_3/interview_notes.txt": "Placeholder content for interview_notes.txt",
              "Methods_Comp_20025/Assignment_1/experiment_data.csv": "Placeholder content for experiment_data.csv",
              "Methods_Comp_20025/Assignment_2/simulation_results.csv": "Placeholder content for simulation_results.csv",
          }

          # Create directories and files
          for relative_path, content in files.items():
              full_path = os.path.join(relative_path)
              os.makedirs(os.path.dirname(full_path), exist_ok=True)
              with open(full_path, "w") as f:
                  f.write(content)

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Add folder structure and placeholder files"
          git push
        
